baseURL = 'http://example.org/'
languageCode = 'de-de'
title = 'Velociraptors Heidelberg'
theme = 'ananke'

[params]
  mainSections = ['post']

[markup]
[markup.goldmark]
  [markup.goldmark.renderer]
    unsafe = true
